version: '3.3'

volumes:
  postgres_data:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 10s
      interval: 1s
      retries: 10

  web:
    image: tjsonyk/foodgram
    restart: always
    depends_on:
      - db
        # condition: service_healthy
    env_file: 
      - ./.env
    volumes:
      - ./static:/var/www/static/
      - ./media:/var/www/media/

  nginx:
    image: nginx:1.19.6
    ports: 
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/static/
      - ./media:/var/www/media/
    depends_on:
      - web