# Generated by Django 3.1.7 on 2021-03-04 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='recipes.amount'),
            preserve_default=False,
        ),
    ]
