# Generated by Django 3.1.7 on 2021-04-02 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210402_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='recipes.dimension'),
        ),
    ]
